/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jeromq.playground;

import java.util.*;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testGetFactors() {
        int n = 20;
        Set<Integer> expected = Set.of(1, 2, 4, 5, 10, 20);
        Set<Integer> actual = Factor.getFactors(n);
        assertTrue(expected.equals(actual));
    }
}
